// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package bpo

import (
	"time"

	"github.com/google/uuid"
)

type BloodPressureObservation struct {
	ID         int
	PersonID   int
	ObservedAt time.Time
	Systolic   int
	Diastolic  int
	Pulse      int
	Irregular  bool
	Comment    string
}

type Person struct {
	ID        int
	Email     string
	CreatedAt time.Time
}

type Session struct {
	ID        uuid.UUID
	PersonID  int
	ExpiresAt time.Time
}
