// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package bpo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BloodPressureObservation struct {
	ID         int32
	ObservedAt pgtype.Timestamp
	Systolic   int32
	Diastolic  int32
	Pulse      int32
	Irregular  bool
	Comment    string
}
