// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package bpo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBloodPressureObservation = `-- name: CreateBloodPressureObservation :one
INSERT INTO blood_pressure_observation
    (observed_at, systolic, diastolic, pulse, irregular, comment, person_id)
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, person_id, observed_at, systolic, diastolic, pulse, irregular, comment
`

type CreateBloodPressureObservationParams struct {
	ObservedAt time.Time
	Systolic   int
	Diastolic  int
	Pulse      int
	Irregular  bool
	Comment    string
	PersonID   int
}

func (q *Queries) CreateBloodPressureObservation(ctx context.Context, arg CreateBloodPressureObservationParams) (BloodPressureObservation, error) {
	row := q.db.QueryRow(ctx, createBloodPressureObservation,
		arg.ObservedAt,
		arg.Systolic,
		arg.Diastolic,
		arg.Pulse,
		arg.Irregular,
		arg.Comment,
		arg.PersonID,
	)
	var i BloodPressureObservation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.PersonID,
		&i.ObservedAt,
		&i.Systolic,
		&i.Diastolic,
		&i.Pulse,
		&i.Irregular,
		&i.Comment,
	)
	return i, err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO person
    (email, created_at)
VALUES ($1, $2)
RETURNING id, email, created_at
`

type CreatePersonParams struct {
	Email     string
	CreatedAt time.Time
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson, arg.Email, arg.CreatedAt)
	var i Person
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO session
    (id, person_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, person_id, expires_at
`

type CreateSessionParams struct {
	ID        uuid.UUID
	PersonID  int
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.PersonID, arg.ExpiresAt)
	var i Session
	err := row.Scan(&i.ID, &i.PersonID, &i.ExpiresAt)
	return i, err
}

const deleteBloodPressureObservation = `-- name: DeleteBloodPressureObservation :exec
DELETE FROM blood_pressure_observation
WHERE person_id = $1
    AND id = $2
`

type DeleteBloodPressureObservationParams struct {
	PersonID int
	ID       int
}

func (q *Queries) DeleteBloodPressureObservation(ctx context.Context, arg DeleteBloodPressureObservationParams) error {
	_, err := q.db.Exec(ctx, deleteBloodPressureObservation, arg.PersonID, arg.ID)
	return err
}

const getBloodPressureObservation = `-- name: GetBloodPressureObservation :one
SELECT
    id,
    observed_at,
    systolic,
    diastolic,
    pulse,
    irregular,
    comment
FROM blood_pressure_observation
WHERE person_id = $1
    AND id = $2
`

type GetBloodPressureObservationParams struct {
	PersonID int
	ID       int
}

type GetBloodPressureObservationRow struct {
	ID         int
	ObservedAt time.Time
	Systolic   int
	Diastolic  int
	Pulse      int
	Irregular  bool
	Comment    string
}

func (q *Queries) GetBloodPressureObservation(ctx context.Context, arg GetBloodPressureObservationParams) (GetBloodPressureObservationRow, error) {
	row := q.db.QueryRow(ctx, getBloodPressureObservation, arg.PersonID, arg.ID)
	var i GetBloodPressureObservationRow
	err := row.Scan(
		&i.ID,
		&i.ObservedAt,
		&i.Systolic,
		&i.Diastolic,
		&i.Pulse,
		&i.Irregular,
		&i.Comment,
	)
	return i, err
}

const getBloodPressureObservations = `-- name: GetBloodPressureObservations :many
SELECT
    id,
    observed_at,
    systolic,
    diastolic,
    pulse,
    irregular,
    comment
FROM blood_pressure_observation
WHERE person_id = $1
ORDER BY observed_at DESC
LIMIT $2
OFFSET $3
`

type GetBloodPressureObservationsParams struct {
	PersonID int
	Limit    int32
	Offset   int32
}

type GetBloodPressureObservationsRow struct {
	ID         int
	ObservedAt time.Time
	Systolic   int
	Diastolic  int
	Pulse      int
	Irregular  bool
	Comment    string
}

func (q *Queries) GetBloodPressureObservations(ctx context.Context, arg GetBloodPressureObservationsParams) ([]GetBloodPressureObservationsRow, error) {
	rows, err := q.db.Query(ctx, getBloodPressureObservations, arg.PersonID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBloodPressureObservationsRow
	for rows.Next() {
		var i GetBloodPressureObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ObservedAt,
			&i.Systolic,
			&i.Diastolic,
			&i.Pulse,
			&i.Irregular,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonByEmail = `-- name: GetPersonByEmail :one
SELECT
    id,
    email,
    created_at
FROM person
WHERE email = $1
`

func (q *Queries) GetPersonByEmail(ctx context.Context, email string) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByEmail, email)
	var i Person
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getSessionById = `-- name: GetSessionById :one
SELECT
    id,
    person_id,
    expires_at
FROM session
WHERE id = $1
`

func (q *Queries) GetSessionById(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionById, id)
	var i Session
	err := row.Scan(&i.ID, &i.PersonID, &i.ExpiresAt)
	return i, err
}

const updateBloodPressureObservation = `-- name: UpdateBloodPressureObservation :one
UPDATE blood_pressure_observation
SET
    observed_at = $1,
    systolic = $2,
    diastolic = $3,
    pulse = $4,
    irregular = $5,
    comment = $6
WHERE id = $7
    AND person_id = $8
RETURNING id, created_at, person_id, observed_at, systolic, diastolic, pulse, irregular, comment
`

type UpdateBloodPressureObservationParams struct {
	ObservedAt time.Time
	Systolic   int
	Diastolic  int
	Pulse      int
	Irregular  bool
	Comment    string
	ID         int
	PersonID   int
}

func (q *Queries) UpdateBloodPressureObservation(ctx context.Context, arg UpdateBloodPressureObservationParams) (BloodPressureObservation, error) {
	row := q.db.QueryRow(ctx, updateBloodPressureObservation,
		arg.ObservedAt,
		arg.Systolic,
		arg.Diastolic,
		arg.Pulse,
		arg.Irregular,
		arg.Comment,
		arg.ID,
		arg.PersonID,
	)
	var i BloodPressureObservation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.PersonID,
		&i.ObservedAt,
		&i.Systolic,
		&i.Diastolic,
		&i.Pulse,
		&i.Irregular,
		&i.Comment,
	)
	return i, err
}
