// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package bpo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBloodPressureObservation = `-- name: CreateBloodPressureObservation :one
INSERT INTO blood_pressure_observation
    (observed_at, systolic, diastolic, pulse, irregular, comment)
VALUES
    ($1, $2, $3, $4, $5, $6)
RETURNING id, observed_at, systolic, diastolic, pulse, irregular, comment
`

type CreateBloodPressureObservationParams struct {
	ObservedAt pgtype.Timestamp
	Systolic   int32
	Diastolic  int32
	Pulse      int32
	Irregular  bool
	Comment    string
}

func (q *Queries) CreateBloodPressureObservation(ctx context.Context, arg CreateBloodPressureObservationParams) (BloodPressureObservation, error) {
	row := q.db.QueryRow(ctx, createBloodPressureObservation,
		arg.ObservedAt,
		arg.Systolic,
		arg.Diastolic,
		arg.Pulse,
		arg.Irregular,
		arg.Comment,
	)
	var i BloodPressureObservation
	err := row.Scan(
		&i.ID,
		&i.ObservedAt,
		&i.Systolic,
		&i.Diastolic,
		&i.Pulse,
		&i.Irregular,
		&i.Comment,
	)
	return i, err
}

const deleteBloodPressureObservation = `-- name: DeleteBloodPressureObservation :exec
DELETE FROM blood_pressure_observation
WHERE id = $1
`

func (q *Queries) DeleteBloodPressureObservation(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBloodPressureObservation, id)
	return err
}

const getBloodPressureObservations = `-- name: GetBloodPressureObservations :many
SELECT
    id,
    observed_at,
    systolic,
    diastolic,
    pulse,
    irregular,
    comment
FROM blood_pressure_observation
`

func (q *Queries) GetBloodPressureObservations(ctx context.Context) ([]BloodPressureObservation, error) {
	rows, err := q.db.Query(ctx, getBloodPressureObservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BloodPressureObservation
	for rows.Next() {
		var i BloodPressureObservation
		if err := rows.Scan(
			&i.ID,
			&i.ObservedAt,
			&i.Systolic,
			&i.Diastolic,
			&i.Pulse,
			&i.Irregular,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBloodPressureObservation = `-- name: UpdateBloodPressureObservation :one
UPDATE blood_pressure_observation
SET
    observed_at = $1,
    systolic = $2,
    diastolic = $3,
    pulse = $4,
    irregular = $5,
    comment = $6
WHERE id = $7
RETURNING id, observed_at, systolic, diastolic, pulse, irregular, comment
`

type UpdateBloodPressureObservationParams struct {
	ObservedAt pgtype.Timestamp
	Systolic   int32
	Diastolic  int32
	Pulse      int32
	Irregular  bool
	Comment    string
	ID         int32
}

func (q *Queries) UpdateBloodPressureObservation(ctx context.Context, arg UpdateBloodPressureObservationParams) (BloodPressureObservation, error) {
	row := q.db.QueryRow(ctx, updateBloodPressureObservation,
		arg.ObservedAt,
		arg.Systolic,
		arg.Diastolic,
		arg.Pulse,
		arg.Irregular,
		arg.Comment,
		arg.ID,
	)
	var i BloodPressureObservation
	err := row.Scan(
		&i.ID,
		&i.ObservedAt,
		&i.Systolic,
		&i.Diastolic,
		&i.Pulse,
		&i.Irregular,
		&i.Comment,
	)
	return i, err
}
